package main

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// chart renders docs/ai-costs.md: the cost of each issue and the cumulative
// cost by week. It depends only on rows, so the same data gives the same file.
func chart(rows []row) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by `make costs` (tokencost chart). Do not edit. -->\n")
	b.WriteString("# Custo de IA\n\n")
	b.WriteString("Custo de tokens do Claude Code por issue, a partir de [`ai-costs.csv`](ai-costs.csv). ")
	b.WriteString("Inclui o `overhead`: chamadas que o Claude Code cobra e o transcript não registra.\n\n")
	if len(rows) == 0 {
		b.WriteString("Sem dados.\n")
		return b.String()
	}
	var last time.Time
	for _, r := range rows {
		if r.End.After(last) {
			last = r.End
		}
	}
	fmt.Fprintf(&b, "Dados até %s.\n\n", last.UTC().Format("2006-01-02"))

	byIssue := map[int]int64{}
	for _, r := range rows {
		byIssue[r.Issue] += r.Cost
	}
	issues := make([]int, 0, len(byIssue))
	for i := range byIssue {
		issues = append(issues, i)
	}
	sort.Ints(issues)
	labels := make([]string, len(issues))
	values := make([]int64, len(issues))
	for i, n := range issues {
		labels[i] = fmt.Sprintf("#%d", n)
		if n == 0 {
			labels[i] = "sem issue"
		}
		values[i] = byIssue[n]
	}
	b.WriteString("## Custo por issue\n\n")
	writeXYChart(&b, "Custo por issue (US$)", "bar", labels, values)

	weeks, cumulative := weeklyCumulative(rows)
	b.WriteString("\n## Custo acumulado por semana\n\n")
	writeXYChart(&b, "Custo acumulado por semana (US$)", "line", weeks, cumulative)
	return b.String()
}

func writeXYChart(b *strings.Builder, title, kind string, labels []string, values []int64) {
	quoted := make([]string, len(labels))
	for i, l := range labels {
		quoted[i] = fmt.Sprintf("%q", l)
	}
	vs := make([]string, len(values))
	for i, v := range values {
		vs[i] = formatCost(v)
	}
	b.WriteString("```mermaid\nxychart-beta\n")
	fmt.Fprintf(b, "    title %q\n", title)
	fmt.Fprintf(b, "    x-axis [%s]\n", strings.Join(quoted, ", "))
	b.WriteString("    y-axis \"US$\"\n")
	fmt.Fprintf(b, "    %s [%s]\n", kind, strings.Join(vs, ", "))
	b.WriteString("```\n")
}

// weeklyCumulative sums the cost of rows up to the end of each week, from the
// week of the first row to the week of the last. A row counts in the week of
// its start; weeks start on Monday, in UTC.
func weeklyCumulative(rows []row) ([]string, []int64) {
	byWeek := map[time.Time]int64{}
	var first, last time.Time
	for _, r := range rows {
		w := weekStart(r.Start)
		byWeek[w] += r.Cost
		if first.IsZero() || w.Before(first) {
			first = w
		}
		if w.After(last) {
			last = w
		}
	}
	var labels []string
	var values []int64
	var sum int64
	for w := first; !w.After(last); w = w.AddDate(0, 0, 7) {
		sum += byWeek[w]
		labels = append(labels, w.Format("2006-01-02"))
		values = append(values, sum)
	}
	return labels, values
}

func weekStart(t time.Time) time.Time {
	t = t.UTC()
	day := time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, time.UTC)
	return day.AddDate(0, 0, -(int(day.Weekday())+6)%7)
}
